
CREATE OR REPLACE PROCEDURE APP_INCLUIR_CLIENTE
(p_ID IN CLIENTE.ID%type,
p_RAZAO_SOCIAL IN CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ IN CLIENTE.CNPJ%type,
p_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%type)
IS
BEGIN
   INCLUIR_CLIENTE(p_ID, p_RAZAO_SOCIAL, p_CNPJ, p_SEGMERCADO_ID, p_FATURAMENTO_PREVISTO);
END;

EXECUTE APP_INCLUIR_CLIENTE(6, 'SEGUNDO CLIENTE INCLUIDO POR USER_APP','23456',2,100000);

SELECT * FROM CLIENTE;


